apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::945491817958:role/eksctl-cicd-demo-nodegroup-ng-1-NodeInstanceRole-1QQDA7NWB0XFI
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-13T14:16:09Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-05-13T14:16:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1763"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f3a3f5c6-1963-4a8e-865f-0adad60992b0
